from .mnist_data_loaders import MnistDataLoader
from .imagenet1k_data_loaders import ImageNet1kDataLoader
from .npz_loaders import NPZDataLoader
from .excel_img_data_loaders import ExcelImgDataLoader
